//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGP {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IGP.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        internal static string Tooltip_Chart_Info {
            get {
                return ResourceManager.GetString("Tooltip Chart Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Filter_Info {
            get {
                return ResourceManager.GetString("Tooltip Filter Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Entity_Info {
            get {
                return ResourceManager.GetString("Tooltip Entity Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Bank_Info {
            get {
                return ResourceManager.GetString("Tooltip Bank Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Army_Info {
            get {
                return ResourceManager.GetString("Tooltip Army Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Highlights_Info {
            get {
                return ResourceManager.GetString("Tooltip Highlights Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_BuildOrder_Info {
            get {
                return ResourceManager.GetString("Tooltip BuildOrder Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Timing_Info {
            get {
                return ResourceManager.GetString("Tooltip Timing Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Hotkey_Info {
            get {
                return ResourceManager.GetString("Tooltip Hotkey Info", resourceCulture);
            }
        }
        
        internal static string Tooltip_Options_Info {
            get {
                return ResourceManager.GetString("Tooltip Options Info", resourceCulture);
            }
        }
    }
}
